Output demo.gif
Set FontSize 16
Set FontFamily "JetBrains Mono"
Set Width 800
Set Height 600
Set WindowBar Colorful
Set Theme "GitHub Dark"
Set TypingSpeed 0.1

Type "make run"
Enter
Sleep 2s
Type "1"    # Select Vanilla
Enter
Sleep 2s
Type "2"    # 2 Scoops
Enter
Sleep 2ms
Type "y"    # Another?
Enter
Sleep 2s
Type "3"    # Select Strawberry
Enter
Sleep 2s
Type "1"    # 1 Scoops
Enter
Sleep 2s
Type "n"    # Another?
Enter
Sleep 3s